[program:vsr-config]
command=node /var/www/www-root/data/www/vsr-config/current/index.js
directory=/var/www/www-root/data/www/vsr-config/current
autostart=true
autorestart=true
startsecs=3
stopwaitsecs=10
user=root
environment=NODE_ENV="production",PORT="3200"
stdout_logfile=/var/log/supervisor/vsr-config.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile=/var/log/supervisor/vsr-config-error.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=5
